name: Generate JSON schema from the Telegram Bot API documentation

# Update the generated schema once per day, but also on commits and pull requests.
on:
  schedule:
    - cron:  '33 3 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install 'poetry' for Python dependencies
        run: pip install poetry

      - name: Generate types, JSON Schema
        run: |-
          poetry run python generate_schema.py jsonschema > schema.json
          poetry run python generate_schema.py python > telegram_bot_api.py

      - name: Commit and push if the schema changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest schema: ${timestamp}" || exit 0
          git push
